stages:
  load_data: 
    cmd: python src/load_data.py --config=params.yaml
    deps: 
    - src/upload_get_data.py
    - src/load_data.py
    - data_given/BBC_News_Train.csv
    - data_given/BBC_News_Test.csv
    outs:
    - data/raw/news_test.csv
    - data/raw/news_train.csv

  process_data:
    cmd: python src/preprocess.py --config=params.yaml
    deps: 
    - src/preprocess.py
    - data/raw/news_train.csv
    outs:
    - data/processed/news_model_data.csv

  train_and_evaluate:
    cmd: python src/train_model.py --config=params.yaml
    deps:
    - src/train_model.py
    - data/processed/news_model_data.csv
    params:
    - train_evaluate.estimators.RandomForestClassifier.params.min_samples_leaf
    - train_evaluate.estimators.RandomForestClassifier.params.max_depth
    - train_evaluate.estimators.RandomForestClassifier.params.n_estimators
    - train_evaluate.estimators.RandomForestClassifier.params.min_samples_split

    metrics:
    - model_reports/scores.json:
        cache: false
    - model_reports/params.json:
        cache: false
    