base: 
  project: News_Article_Sorting_NLP_Machine-Learning
  random_state: 42

data_source: 
  train_source_data: data_given/BBC_News_Train.csv
  test_source_data: data_given/BBC_News_Test.csv

load_data:
  raw_train_data_path: data/raw/news_train.csv
  raw_test_data_path: data/raw/news_test.csv
  

process_data:
  news_model_data_path: data/processed/news_model_data.csv